apiVersion: skaffold/v3
kind: Config
metadata:
  name: app
build:
  artifacts:
    - image: andrewkarma/authentservice
      context: src/services/authentservice
  tagPolicy:
    gitCommit: {}
  local:
    useBuildkit: false
manifests:
  kustomize:
    paths:
      - kubernetes-manifests-dev
deploy:
  kubectl: {}
profiles:
  - name: gcb
    build:
      googleCloudBuild:
        diskSizeGb: 300
        machineType: N1_HIGHCPU_32
        timeout: 5000s
  - name: debug
    activation:
      - command: debug
    patches:
      - op: replace
        path: /build/artifacts/7/docker/dockerfile
        value: Dockerfile.debug
  - name: network-policies
    patches:
      - op: add
        path: /manifests/kustomize/paths/1
        value: kustomize/components/network-policies
  - name: dev
    activation:
      - command: dev
    build:
      artifacts:
        - image: andrewkarma/authentservice
          context: src/services/authentservice
          docker:
            buildArgs:
              ENV: development
          sync:
            manual:
              - src: 'src/**/*.ts'
                dest: .
        - image: andrewkarma/keys
          context: src/services/user_registration_keyservice
          docker:
            buildArgs:
              ENV: development
          sync:
            manual:
              - src: 'src/**/*.ts'
                dest: .
  - name: kai
    activation:
      - command: kai
    build:
      artifacts:
        - image: andrewkarma/authentservice
          context: src/services/authentservice
          docker:
            buildArgs:
              ENV: kai
