 
{{- $namespace := .Release.Namespace | default .Values.namespace }}

{{- range $serviceName, $serviceConfig := .Values.services }}
  {{- with $serviceConfig.mongo }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .serviceName }}
  namespace: {{ $namespace }}
spec:
  selector:
    app: {{ .name }}
  ports:
    - name: "mongo"
      port: {{ .port | default 27017 | int }}
      targetPort: {{ .port | default 27017 | int }}
  type: ClusterIP
---
  {{- end }}
{{- end }}
