apiVersion: v1
kind: Service
metadata:
  name: productservice
  namespace: deployments
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
    prometheus.io/port: '50051'
spec:
  type: ClusterIP
  selector:
    app: productservice
  ports:
    - name: http
      port: 80
      targetPort: 50051
