apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentservice
spec:
  selector:
    matchLabels:
      app: authentservice
  template:
    metadata:
      labels:
        app: authentservice
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: server
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: false # change sum things here to make it work better :)
          image: andrewkarma/authentservice
          resources:
            limits:
              memory: '512Mi'
              cpu: '500m'
            requests:
              memory: '256Mi'
              cpu: '250m'
          ports:
            - containerPort: 50051
          env:
            - name: PORT
              value: '50051'
            - name: MONGO_DB
              value: 'mongodb://auth-mongo-srv:27017/authenthication'
            - name: RabbitMQ
              value: 'amqp://guest:guest@auth-rabbitmq-srv:5672/'
            - name: REDIS
              value: 'redis://auth-redis-srv:6379/'
---
apiVersion: v1
kind: Service
metadata:
  name: authentservice
spec:
  type: ClusterIP
  selector:
    app: authentservice
  ports:
    - name: port
      port: 80
      targetPort: 50051

---
apiVersion: v1
kind: Service
metadata:
  name: authentservice-external
spec:
  type: LoadBalancer
  selector:
    app: authentservice
  ports:
    - name: http
      port: 80
      targetPort: 50051
