apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - authentservice.yaml
  - authmongo.yaml
  - rabbitmq.yaml
  - redis.yaml
  - keys.yaml
  - productsmysql.yaml
  - products.yaml
