apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-mongo
spec:
  selector:
    matchLabels:
      app: product-mongo
  template:
    metadata:
      labels:
        app: product-mongo
    spec:
      containers:
        - name: product-mongo
          image: mongo
          ports:
            - containerPort: 27017
          resources:
            limits:
              memory: '512Mi'
              cpu: '500m'
            requests:
              memory: '256Mi'
              cpu: '250m'
          volumeMounts:
            - name: mongo-data
              mountPath: /data/auth-db
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo-pvccz

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pvzz
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /path/to/host/folder

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvccz
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual

---
apiVersion: v1
kind: Service
metadata:
  name: product-mongo-srv
spec:
  selector:
    app: product-mongo
  type: LoadBalancer
  ports:
    - name: product-mongo-srv
      port: 27017
      targetPort: 27017
