replicaCount: 1

image:
  repository: prom/prometheus
  tag: v2.41.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9090

config:
  global:
    scrape_interval: 15s
  scrape_configs:
    - job_name: 'external-metrics'
      static_configs:
        - targets: ['backend-tests.conceptocar.xyz:443']
      scheme: https
      metrics_path: '/auth/metrics'
      relabel_configs:
        - source_labels: [__address__]
          target_label: instance
