name: Backend CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Start Minikube
        uses: medyagh/setup-minikube@master

      - name: Authenticate Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Install dependencies
        run: npm install
        working-directory: backend/src/services/authentservice

      - name: Build the project
        run: npm run build
        working-directory: backend/src/services/authentservice

      - name: Install Skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
          chmod +x skaffold
          sudo mv skaffold /usr/local/bin

      - name: Run Skaffold in Background
        run: skaffold dev -p kai --port-forward --log-level debug &
        working-directory: backend

      - name: Wait for service to be ready
        run: |
          echo "Waiting for service to be ready..."
          sleep 70

      - name: kubectl pods
        run: |
          kubectl get pods

      - name: kubectl pods
        run: |
          kubectl get services authentservice

      - name: Test /health endpoint
        run: |
          kubectl port-forward svc/authentservice 50051:50051 --log-level debug &
          sleep 5
          curl -f http://localhost:50051/health || exit 1
