name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  ci:
    name: Run CI Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      #   - name: Authenticate to Google Cloud
      #     uses: google-github-actions/auth@v1
      #     with:
      #       credentials_json: ${{ secrets.GCP_SA_KEY }}

      #   - name: Set up Google Cloud SDK
      #     uses: google-github-actions/setup-gcloud@v1
      #     with:
      #       project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Install Skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
          chmod +x skaffold
          sudo mv skaffold /usr/local/bin
        working-directory: backend

      - name: Authenticate Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      # Uncomment if using Google Container Registry (GCR) instead of Docker Hub
      # - name: Authenticate Google Cloud Container Registry
      #   uses: google-github-actions/auth@v1
      #   with:
      #     credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Start Skaffold
        run: |
          skaffold dev --profile dev &
          sleep 10
        working-directory: backend

      - name: Wait for Application to be Ready
        run: |
          # Wait until the deployment is ready
          kubectl rollout status deployment <deployment-name> --timeout=120s
        working-directory: backend

      - name: Port Forward Service
        run: |
          kubectl port-forward svc/<service-name> 8080:3000 &
          sleep 5
        working-directory: backend

      - name: Test /health Endpoint
        run: |
          echo "Waiting for health check to pass..."
          for i in {1..10}; do
            if curl -s http://localhost:8080/health | grep "OK"; then
              echo "Health check passed."
              exit 0
            fi
            echo "Health check failed. Retrying in 5 seconds..."
            sleep 5
          done
          echo "Health check failed after multiple attempts."
          exit 1
        working-directory: backend
